language: android

jdk:
  - oraclejdk8

env:
  global:
  - MALLOC_ARENA_MAX=2

sudo: false

android:

   components:
    # The BuildTools version used by your project
    - tools
    - build-tools-27.0.2

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-26

before_install:
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
  - yes | sdkmanager "platforms;android-27"

notifications:
  email: false
  slack: alteregosolutions:q2eicS9FFWEEyrmn55SPa5mT#android-bound

cache:
  directories:
    - $HOME/.gradle

script: ./gradlew clean assemble dependencyUpdates test
