language: android

jdk:
  - oraclejdk7

env:
  global:
  - MALLOC_ARENA_MAX=2

sudo: false

android:

   components:
    # The BuildTools version used by your project
    - tools
    - build-tools-26.0.1

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-26

before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA_HOME=$JAVA7_HOME

notifications:
  email: false
  slack: alteregosolutions:q2eicS9FFWEEyrmn55SPa5mT#android-bound

cache:
  directories:
    - $HOME/.gradle

script: ./gradlew clean assembleDebug
